services:
  - type: web
    name: telegram-odds-bot
    env: python
    region: virginia
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --workers 1 --threads 8 --timeout 0"
    envVars:
      - key: BOT_TOKEN
        sync: false
